<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SephPlanner.DataTool</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SephPlanner.Core\SephPlanner.Core.csproj" />
  </ItemGroup>
</Project>
